import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WagmiProvider from "@/WagmiProvider";
import Header from "@/components/header";
import { ScrollArea } from "@/components/ui/scroll-area";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WagmiProvider>
          <div className="flex flex-col h-[100vh] overflow-hidden">
            <Header />
            <ScrollArea className="flex-1 h-[calc(100vh-72px)] w-full">
              {children}
            </ScrollArea>
          </div>
        </WagmiProvider>
      </body>
    </html>
  );
}
